// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4RkR1Nj2qPTzXRJMgV-ikFtYjr3AmKn4',
    appId: '1:395175017710:web:5d8e442e02d5681b1d07ff',
    messagingSenderId: '395175017710',
    projectId: 'evently-c16',
    authDomain: 'evently-c16.firebaseapp.com',
    storageBucket: 'evently-c16.firebasestorage.app',
    measurementId: 'G-NFLL41W84X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA21tgu1POxICY-vpWqXNMx4CRN3rVdsbg',
    appId: '1:395175017710:android:235071a979b5d24f1d07ff',
    messagingSenderId: '395175017710',
    projectId: 'evently-c16',
    storageBucket: 'evently-c16.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4RkR1Nj2qPTzXRJMgV-ikFtYjr3AmKn4',
    appId: '1:395175017710:web:edb0fb07f2a848011d07ff',
    messagingSenderId: '395175017710',
    projectId: 'evently-c16',
    authDomain: 'evently-c16.firebaseapp.com',
    storageBucket: 'evently-c16.firebasestorage.app',
    measurementId: 'G-8R0PNZX7F0',
  );

}